# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kondal Ramidi
tagline:          'Portfolio'
url:              https://Kondal-Ramidi.github.io/

author:
  name:           'Kondal Ramidi'
  github:         Kondal-Ramidi

paginate:         5

# Custom vars
version:          2.1.0

plugins: 
  - jekyll-paginate
  - jekyll-gist
  

